const OneSignal = {
  initialize: () => {},
  login: () => {},
  logout: () => {},
  User: {
    pushSubscription: {
      optIn: () => {},
      optOut: () => {},
      getIdAsync: () => Promise.resolve(null),
      id: null,
      token: null,
      optedIn: false,
      addEventListener: () => {},
      removeEventListener: () => {},
    },
    addTag: () => {},
    removeTag: () => {},
    addTags: () => {},
    removeTags: () => {},
    getTags: () => Promise.resolve({}),
    addAlias: () => {},
    removeAlias: () => {},
    addAliases: () => {},
    removeAliases: () => {},
    addEmail: () => {},
    removeEmail: () => {},
    addSms: () => {},
    removeSms: () => {},
  },
  Notifications: {
    requestPermission: () => Promise.resolve(false),
    getPermissionAsync: () => Promise.resolve(false),
    hasPermission: () => false,
    permissionNative: () => Promise.resolve('notDetermined'),
    canRequestPermission: () => Promise.resolve(false),
    addEventListener: () => {},
    removeEventListener: () => {},
    clearAll: () => {},
  },
  InAppMessages: {
    addTrigger: () => {},
    removeTrigger: () => {},
    addTriggers: () => {},
    removeTriggers: () => {},
    clearTriggers: () => {},
    setLifecycleHandler: () => {},
    setClickHandler: () => {},
    paused: () => Promise.resolve(false),
    setPaused: () => {},
  },
  Location: {
    requestPermission: () => {},
    isShared: () => Promise.resolve(false),
    setShared: () => {},
  },
  Debug: {
    setLogLevel: () => {},
    setAlertLevel: () => {},
  },
  LiveActivities: {
    enter: () => Promise.resolve(),
    exit: () => Promise.resolve(),
    setPushToStartToken: () => Promise.resolve(),
    removePushToStartToken: () => Promise.resolve(),
  },
  consentGiven: false,
  consentRequired: false,
  setConsentGiven: () => {},
  setConsentRequired: () => {},
};
module.exports = { OneSignal, default: OneSignal };
module.exports.OneSignal = OneSignal;
module.exports.default = OneSignal;
